### PR TITLE
migrate to mit license

### PR DESCRIPTION
**Pull request by Eomm**
This is an automatic PR created with [massive-wax](https://github.com/Eomm/massive-wax)!

### CODE REVIEW

**Comment by wesleytodd** [comment]
Cool, I will add you to the org so you can merge these yourself (at work so I might wait until later tonight).  One thing we might want to do before we merge this is decide on how to attribute the license to the group.  For example node uses:

https://github.com/nodejs/node/blob/master/LICENSE#L4

```
Copyright Node.js contributors. All rights reserved.
```

Do we want to say instead `Node.js Package Maintenance Contributors`?

**Comment by Eomm** [comment]
> Do we want to say instead Node.js Package Maintenance Contributors?

I would not limit to one WG, I think the default should be OK
I will update the PRs adding this feature 😄

**Comment by Eomm** [comment]
@wesleytodd done for all the PRs 👍

**Comment by wesleytodd** [comment]
Awesome @Eomm, thanks!

**Pull request merged**
